# Generated by Django 4.2 on 2026-01-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grade_level', models.CharField(help_text="e.g., 'Class 10', 'Grade 9'", max_length=50)),
                ('board', models.CharField(default='NCERT', help_text='e.g., NCERT, CBSE, State Board', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order within course')),
                ('estimated_hours', models.IntegerField(default=1, help_text='Estimated learning time in hours')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='HTML content or markdown')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL', null=True)),
                ('order', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('best_quiz_score', models.IntegerField(default=0, help_text='Best score in % (0-100)')),
                ('proficiency_level', models.CharField(choices=[('not_started', 'Not Started'), ('attempted', 'Attempted'), ('proficient', 'Proficient'), ('mastery', 'Mastery')], default='not_started', max_length=20)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'unique_together': {('student', 'unit')},
            },
        ),
    ]
