# Generated by Django 4.2 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_unit_lesson_studentprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, help_text='Course credits'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, help_text='Instructor name', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisite courses'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_area',
            field=models.CharField(default='General', help_text='e.g., Computer Science, Mathematics', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=40, help_text='Total duration in hours'),
        ),
    ]
