# Generated by Django 4.2 on 2026-01-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skilltag_practiceproblem_learningobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource_explanation',
            field=models.TextField(blank=True, help_text='Why this resource is useful'),
        ),
    ]
