# Generated by Django 4.2 on 2026-01-21 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_lesson_resource_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField(help_text='AI-generated detailed explanation')),
                ('youtube_query', models.CharField(help_text='Search query for specific concept video', max_length=200)),
                ('mastery_weight', models.FloatField(default=1.0, help_text='Weight for progress calculation (1.0 = standard)')),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.IntegerField(default=0, help_text='0-100 score')),
                ('is_weak', models.BooleanField(default=False, help_text='Flagged for revision')),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='career_tags',
            field=models.JSONField(default=list, help_text='List of career tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(default=list, help_text='List of learning outcomes'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD'), ('PROF', 'Professional')], default='UG', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Visual structure data'),
        ),
        migrations.DeleteModel(
            name='StudentBookmark',
        ),
    ]
