# Generated by Django 4.2 on 2026-01-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_concept_conceptmastery_course_career_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='conceptmastery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conceptmastery',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='conceptmastery',
            name='student',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='prerequisite_skills',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='skills_learned',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='practiceproblem',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentbadge',
            name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='ConceptMastery',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='LearningObjective',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='PracticeProblem',
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
        migrations.DeleteModel(
            name='StudentBadge',
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
