# Generated by Django 4.2 on 2026-02-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseunit",
            name="content",
            field=models.TextField(
                blank=True, help_text="Main content/notes for this unit"
            ),
        ),
    ]
