# Generated by Django 4.2 on 2026-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseunit_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='overview',
            field=models.TextField(blank=True, help_text='Syllabus/learning objectives for this unit'),
        ),
    ]
