# Generated by Django 4.2 on 2026-02-07 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_userunitcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('taxonomy_level', models.CharField(choices=[('remember', 'Remembering'), ('understand', 'Understanding'), ('apply', 'Applying'), ('analyze', 'Analyzing'), ('evaluate', 'Evaluating'), ('create', 'Creating')], default='remember', max_length=20)),
                ('difficulty_index', models.FloatField(default=0.5, help_text='0.0 to 1.0 (Easy to Hard)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='course.courseunit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_percentage', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0, help_text='Study streak/consistency factor')),
                ('exam_date_goal', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User course readinesses',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Mastery score 0-100')),
                ('confidence_level', models.FloatField(default=0.0, help_text='User self-reported confidence 0-100')),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('retention_index', models.FloatField(default=1.0, help_text='Estimated memory retention (0-1)')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.conceptnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User concept masteries',
                'unique_together': {('user', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('prereq', 'Prerequisite'), ('related', 'Related'), ('part_of', 'Part Of')], default='prereq', max_length=15)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='course.conceptnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='course.conceptnode')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
