# Generated by Django 4.2 on 2026-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_aistudyinsight_studyactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseunit",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="Optional file upload for the lesson",
                null=True,
                upload_to="course_materials/",
            ),
        ),
    ]
