# Generated by Django 4.2 on 2026-02-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_extracted_text_course_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_materials",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="course.courseunit",
            ),
        ),
    ]
