# Generated by Django 4.2 on 2026-02-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0009_coursematerial_course_alter_coursematerial_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color_theme",
            field=models.CharField(
                default="#6366f1",
                help_text="Hex code for UI personalization",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="e.g. Machine Learning, Cardiology",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="key_topics",
            field=models.JSONField(
                blank=True, default=list, help_text="List of important topics/concepts"
            ),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="summary",
            field=models.TextField(blank=True, help_text="AI-generated summary"),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("tutor", "AI Tutor"),
                            ("reading", "Reading"),
                            ("flashcards", "Flashcards"),
                            ("research", "Research"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(help_text="Time spent in minutes"),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("important_concepts", models.JSONField(blank=True, default=list)),
                ("glossary_terms", models.JSONField(blank=True, default=dict)),
                ("embeddings_status", models.BooleanField(default=False)),
                ("last_processed", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context",
                        to="course.course",
                    ),
                ),
            ],
        ),
    ]
