# Generated by Django 4.2 on 2026-02-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_course_color_theme_course_difficulty_course_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="course.course",
                    ),
                ),
            ],
        ),
    ]
