# Generated by Django 4.2 on 2026-02-12 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_coursenotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
