# Generated by Django 4.2 on 2026-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_coursematerial_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="page_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
