# Generated by Django 4.2 on 2026-02-25 09:05

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_course_page_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="executive_summary",
            field=models.TextField(
                blank=True, help_text="Cached AI-generated summary of the course"
            ),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="file",
            field=models.FileField(upload_to=course.models.course_material_upload_path),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("ppt", "PowerPoint"),
                    ("image", "Image/Diagram"),
                    ("text", "Text/Markdown"),
                ],
                max_length=10,
            ),
        ),
    ]
