# Generated by Django 6.0.1 on 2026-03-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_quizchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="flashcard_chunk_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FlashcardChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_chunks",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
