# Generated by Django 4.2 on 2026-01-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('Foundation', 'Foundation'), ('Developing', 'Developing'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced'), ('Mastery', 'Mastery')], max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('is_scenario_based', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
