# Generated by Django 4.2 on 2026-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='input_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='outcome',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
