# Generated by Django 4.2 on 2026-04-20 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_coursematerial_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0002_activitylog_input_type_activitylog_outcome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenTimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screen_time_logs",
                        to="course.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="screentimelog",
            index=models.Index(
                fields=["user", "tool_name"], name="analytics_s_user_id_1d124f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screentimelog",
            index=models.Index(
                fields=["started_at"], name="analytics_s_started_b2db4d_idx"
            ),
        ),
    ]
