# Generated by Django 4.2 on 2026-04-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_coursematerial_display_name'),
        ('analytics', '0003_screentimelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='course.course'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='app_name',
            field=models.CharField(choices=[('ai_tutor', 'AI Tutor'), ('learning_support', 'Learning Support'), ('flashcard', 'Flashcard Generator'), ('lor', 'LOR Generator'), ('course', 'Course Management'), ('system', 'System Content')], max_length=50),
        ),
    ]
