# Generated by Django 4.2 on 2026-01-22 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard_generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="is_known",
        ),
        migrations.RemoveField(
            model_name="flashcard",
            name="review_count",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="box",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("QA", "Question & Answer"),
                    ("Definition", "Definition"),
                    ("Example", "Example"),
                    ("MCQ", "Multiple Choice"),
                ],
                default="QA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Extra explanation or hint", null=True
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="next_review_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
