# Generated by Django 4.2 on 2026-01-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard_generator", "0002_remove_flashcard_is_known_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="exam_tip",
            field=models.TextField(blank=True, help_text="Exam-focused tip", null=True),
        ),
    ]
