# Generated by Django 4.2 on 2026-02-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_courseunit_content"),
        ("flashcard_generator", "0003_flashcard_exam_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcarddeck",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flashcard_decks",
                to="course.courseunit",
            ),
        ),
    ]
