# Generated by Django 4.2 on 2026-02-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_courseunit_uploaded_file"),
        ("flashcard_generator", "0004_flashcarddeck_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcarddeck",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flashcard_decks",
                to="course.course",
            ),
        ),
    ]
