# Generated by Django 4.2 on 2026-02-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_course_color_theme_course_difficulty_course_subject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="course.course",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="difficulty",
            field=models.CharField(default="Medium", max_length=20),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="generated_questions",
            field=models.JSONField(
                blank=True, default=list, help_text="Stored questions for review"
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
