# Generated by Django 4.2 on 2026-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizattempt_course_quizattempt_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="failed_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Metadata from failed questions for summary",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="used_chunk_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IDs of KnowledgeStore chunks used in this quiz",
            ),
        ),
    ]
