# Generated by Django 4.2 on 2026-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_question_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="AI-generated or manual explanation for the correct answer",
            ),
        ),
    ]
