# Generated by Django 4.2 on 2026-02-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0013_course_page_count"),
        ("quiz", "0005_question_explanation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="failed_topics",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="used_chunk_ids",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="generated_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stored original questions for this specific attempt",
            ),
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("selected_option", models.CharField(max_length=255)),
                ("correct_option", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField()),
                ("explanation", models.TextField(blank=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentQuestionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_hash", models.CharField(db_index=True, max_length=64)),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course", "question_hash")},
            },
        ),
    ]
