# Generated by Django 4.2 on 2026-02-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Faculty", "Faculty")], max_length=50
            ),
        ),
    ]
