# Generated by Django 4.2 on 2026-02-09 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_courseunit_uploaded_file"),
        ("ai_tutor", "0002_chat_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chats",
                to="course.course",
            ),
        ),
    ]
