# Generated by Django 4.2 on 2026-01-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LetterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                (
                    "course_degree",
                    models.CharField(
                        help_text="e.g. B.Tech Computer Science", max_length=255
                    ),
                ),
                ("institution_name", models.CharField(max_length=255)),
                (
                    "duration_of_association",
                    models.CharField(
                        help_text="e.g. 2 years, 2022-2024", max_length=100
                    ),
                ),
                (
                    "academic_performance",
                    models.TextField(
                        help_text="Grades, class rank, specific subject strengths"
                    ),
                ),
                (
                    "technical_skills",
                    models.TextField(
                        help_text="Programming languages, tools, technologies"
                    ),
                ),
                (
                    "soft_skills",
                    models.TextField(help_text="Communication, leadership, teamwork"),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="Projects, internships, publications, awards",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("higher_studies", "Higher Studies (Masters/PhD)"),
                            ("job", "Job Application"),
                            ("scholarship", "Scholarship Application"),
                            ("research", "Research Position"),
                            ("other", "Other"),
                        ],
                        default="higher_studies",
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Focused"),
                            ("research", "Research Oriented"),
                            ("industry", "Industry/Professional"),
                            ("strong", "Strongly Recommended"),
                            ("neutral", "Balanced/Neutral"),
                        ],
                        default="academic",
                        max_length=50,
                    ),
                ),
                ("generated_letter", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
