# Generated by Django 4.2 on 2026-01-21 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Topic where help was requested", max_length=255
                    ),
                ),
                (
                    "hints_used",
                    models.IntegerField(
                        default=0, help_text="Number of hints provided"
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, help_text="Time spent in support session"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
