# Generated by Django 4.2 on 2026-02-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0012_coursematerial_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", models.JSONField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge Store",
            },
        ),
    ]
